[SFA-58] [SFA-47] WIP: UI/match details
SPahooja/SocialSports pull request #19
Opened 2021-07-05 17:52 UTC by akassab

# UI/match details
- Created activity_match_details.xml using constaint layout:  2177397893984ad541bc9090bb755e794b85021d
- Created `MatchDetailsActivity`: 861c8c4e3e2bf19565a3a24f98e1bd4a5c2f0c2e
- Connected @anthea-li recycler view items to `MatchDetailsActivity `using `onClickListener`, `Intent`, and passed data using `putStringArrayListExtra(..)`: e1be627f2b3bd8a9853f79abfb1c0f480127dfe5

# GIF 
![Demo](https://user-images.githubusercontent.com/15854649/124505733-26c2cc00-dd98-11eb-85cd-eddd74bac358.gif)

2021-07-05 18:13 UTC, akassab commented
@anthea-li. The titles shown in the GIF are different but for the most part, everything else is the same. I'm thinking we could make it more obvious that the two cards are different by changing the location, match capacity, etc.

2021-07-06 06:08 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/MatchDetailsActivity.kt
> +class MatchDetailsActivity : AppCompatActivity() {
Do you really need an activity? THis can be done with the recommended way of using a fragment that also follows the rest of app design

2021-07-06 06:10 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/MatchDetailsActivity.kt
> +        val matchTitle: TextView = findViewById(R.id.match_title)
instead of finding the ids, you can use bindings(refer mainActivity) to make code more readable and resilient against changes

2021-07-06 06:11 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/MatchDetailsActivity.kt
> +        val match: ArrayList<String>? = intent.getStringArrayListExtra("match")
best practice prevents views talking amongst each other to avoid one point of failure, such communication should go through the view model

2021-07-06 06:14 UTC, SPahooja commented on app/src/main/res/layout/activity_match_details.xml
> +        android:id="@+id/textView8"
better id naming would help with the bindings

2021-07-06 06:15 UTC, SPahooja requested changes
To fix the pipeline, you need to run lint locally and push the changes

2021-07-06 18:54 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/MatchDetailsActivity.kt
> +class MatchDetailsActivity : AppCompatActivity() {
Yes I do.

Consider when someone click on the same match from either
"My Games" and "Find". Then there will be two fragments that are identical. Lots of apps like Uber eats, Recipe apps use a basic activity for their own details view which get triggered from a fragment like seen in the GIF.

I also don't think the _entire ui of our app_ has to exist ontop of the bottom navbar,it isn't really a required or recommended ui design practice

2021-07-06 18:55 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/MatchDetailsActivity.kt
> +        val matchTitle: TextView = findViewById(R.id.match_title)
Don't think that is important to do right now since markers will not look at the code yet. But definitely, something to do for the next deliverable (or if someone else wanted to take on this before Wednesday night)

2021-07-06 20:09 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/MatchDetailsActivity.kt
> +        val match: ArrayList<String>? = intent.getStringArrayListExtra("match")
I believe we should do that eventually

2021-07-06 20:14 UTC, akassab commented
Just like I mentioned at the conference, I won't be able to work on this much anymore this week. @aaronchlam mentioned he would take over so I'm thinking I merge this so he can get started

2021-07-08 10:15 UTC, SPahooja submitted a review, later dismissed

2021-07-08 15:43 UTC, anthea-li approved these changes

2021-07-08 16:02 UTC, merged