Add joinMatch and leaveMatch functions to FirebaseMatchRepository
SPahooja/SocialSports pull request #57
Opened 2021-07-29 06:54 UTC by cyamonide

## Description

Title.

2021-07-29 13:59 UTC, aaronchlam requested changes

2021-07-29 13:59 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/services/match/FirebaseMatchRepository.kt
> +        edit(newMatch)
I think editing the match is actually saving the whole object again. We can get the ABA problem when 2 people join the match at the same time. Firebase has a way to add to an array. I think this is an atomic operation? https://firebase.google.com/docs/firestore/manage-data/add-data#update_elements_in_an_array

2021-07-30 04:33 UTC, cyamonide commented on app/src/main/java/com/uwcs446/socialsports/services/match/FirebaseMatchRepository.kt
> +        edit(newMatch)
Updated the PR to add to the array instead of rewriting entire matches at a time.

2021-07-30 04:35 UTC, aaronchlam approved these changes

2021-07-30 04:38 UTC, merged