[SFA-73] [SFA-102]  Rating System Real Data
SPahooja/SocialSports pull request #79
Opened 2021-08-07 18:57 UTC by akassab

# Preface
- Builds off of #75 but uses actual players for the game that was joined
- Added userRating and numRatings to the user entity on firebase
- If a user is given no ratings (0 stars) it is assumed no rating was given
- In this video the notification occurs as soon as you click "join" but that is just for testing purposes, in reality, the notification will only be triggered AFTER the game is completed.
- Uses ViewModel and Hilt dependency injection

# Demonstration
https://user-images.githubusercontent.com/15854649/128610889-cc270733-2108-478e-95ca-6ae211705bac.mp4

https://user-images.githubusercontent.com/15854649/128610887-56a98e84-dc32-4ec5-bec9-2217783604e3.mp4

2021-08-07 20:32 UTC, aaronchlam requested changes

2021-08-07 20:32 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingViewModel.kt
> +                    userRepository.upsert(userUpdated)
Editing ratings via upsert of the user will lead to race conditions. 

If Players A and B are rating Player C at the same time then one will overwrite the other. The outcome is that Player C only gets 1 more rating when there's supposed to be 2 more ratings.

Also Users should not be editing each other.

2021-08-07 20:32 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
> +                            matchRatingViewModel.ratePlayers(matchRatingAdapter.getPlayerRatingList())
Why get the players from the adapter? That's the data from another view? This data should be from the ViewModel.

2021-08-07 20:32 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingViewModel.kt
> +                it.id != currentUser?.uid ?: false
Since currentUser can actually be null, he can rate himself.

2021-08-07 20:32 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
This activity needs to check if the player is logged in on create because the user can be logged out. Clicking on the notification allows the user rate everyone, including themselves. It also puts the app in a strange state after rating where it allows the user to go past the login screen but there's no way to log out. See attached video.


https://user-images.githubusercontent.com/6414135/128612796-85c85f12-aee9-4197-b5b7-6bdb9bc8a1cf.mp4

2021-08-07 20:32 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/services/user/UserAssembler.kt
> +        rating = rating,
Ratings shouldn't be a simple moving average. Lower I discuss how we have a race condition due to updating users.

Ratings should be its own collection where we know which user rated who and for which match. This is so that users can rate simultaneously.

2021-08-07 20:32 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingViewModel.kt
> +    private val currentUser = currentUserRepository.getUser()
As mentioned in a comment on the activity, the user can be logged out so this user can be null.

2021-08-07 20:32 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingViewModel.kt
> +        if (fetchedMatch != null) {
If the match is null then `_ready` won't get set to true. Won't this cause the screen is hang on loading?

2021-08-07 20:32 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
> +            matchRatingViewModel.fetchMatchPlayers(matchId!!)
Does this screen have any indicators that we're loading the match?

2021-08-07 20:39 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
great catch, also by the demo it seems we can leave and join past matches multiple times and keep on rating the users.I don't think that should be allowed

2021-08-07 20:41 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/services/user/UserAssembler.kt
> +        rating = rating,
I agree, as an idea you can create documents in a rating collection like user1_user2 or something similar to support concurrency however some thought would be needed on the computation on the avg rating which can get tricky with increasing collection size

2021-08-07 21:39 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
Ya, past matches shouldn't show a leave/join or edit button. I can fix this.

2021-08-07 22:09 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>  class MatchRatingActivity : AppCompatActivity() {
Is there an issue that prevents you from using fragments similar to literally every other view? If so, please do share

2021-08-07 22:10 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
> +                    val submitRatingButton: Button = findViewById(R.id.submit_rating_button)
should use bindings over finding by id

2021-08-07 22:11 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingViewModel.kt
> +            val fetchedTeamTwo = userRepository.findByIds(fetchedMatch.teamTwo)
should query the db once with all the user ids

2021-08-07 22:14 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingViewModel.kt
> +                    val user = _players.value?.get(index)!!
this is again the bad practice mentioned before, use of non-null assertion is only for cases when YOU KNOW it will be non null, where for getting an index of a list is not a safe op hence please handle the null to avoid app crashes

2021-08-07 22:15 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingViewModel.kt
> +                    val userUpdated = User(user.id, user.name, ((user.rating * user.numRatings) + rating) / (user.numRatings + 1), user.numRatings + 1)
for readability always prefer using helper functions, which makes code easier to write, debug, review and maintain

2021-08-07 23:21 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>  class MatchRatingActivity : AppCompatActivity() {
See PR #75

2021-08-07 23:34 UTC, akassab commented
@aaronchlam @SPahooja Thank you for the comments 💯 Going to continue working on this tomorrow morning as I must study for my exam coming up. Feel free to work on this branch if you really want to in the team time :)

2021-08-08 00:48 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingViewModel.kt
> +                    userRepository.upsert(userUpdated)
Interesting point! Takes me back to concurrency in my OS course 🙂. I'll think about this one but I have a Exam in a few days so I can't promise anything unfortunately. On the bright side the TA said we shouldn't worry too much about race conditions 😅

2021-08-08 01:03 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
> +                            matchRatingViewModel.ratePlayers(matchRatingAdapter.getPlayerRatingList())
Exactly what I was trying to avoid and I'm glad you brought it up. 

Each rating bar is set up by the ViewPagerAdapter method. Then I similar to how we have a onClick method in the MatchListAdapter. I did this for the sake of consistency. 

Now as I switch through fragments of the math detail view pager I saw that some rating-bars would be cleared... so I thought we had to save the states of the stars somewhere incase the user wanted to go back and fix a rating. So I saved them in the list of floats in the adapter as well.

Then we have the submit button which is outside if the adapter, and I needed to grab this list of floats from the adapter as well.


....

Is it good practice to inject the viewmodel in the adapter? I wasn't entirely sure? Or do you have a suggestion?

2021-08-08 02:49 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
> +                            matchRatingViewModel.ratePlayers(matchRatingAdapter.getPlayerRatingList())
Pass a callback into Adapter constructor. The callback would be a method from the ViewModel to update the list of ratings.

2021-08-08 03:20 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>  class MatchRatingActivity : AppCompatActivity() {
care to explain?

2021-08-08 04:11 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>  class MatchRatingActivity : AppCompatActivity() {
There is a very lengthy discussion about this in that PR just I just tagged, scroll down and you'll see 🙂

2021-08-08 04:13 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>      override fun onCreate(savedInstanceState: Bundle?) {
I fixed the leave/join button problem in #83.

2021-08-08 16:35 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>  class MatchRatingActivity : AppCompatActivity() {
That discussion isn't addressed completely Ayman, so it's appreciated if the concern is addressed in time instead of holding it off till 11th hour and expecting the review to be approved

2021-08-08 18:47 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>  class MatchRatingActivity : AppCompatActivity() {
I'm sorry you feel that way @SPahooja but I and @aaronchlam talked about it in that PR? Whatever I have to say about using a fragment would be just me copying and pasting what I said before. See #75

2021-08-08 18:55 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
>  class MatchRatingActivity : AppCompatActivity() {
Also, the purpose of this PR is to address the real data of the rating system. What you are talking about was discussed **48+** hours ago to be exact. Also please be [kind ](https://hackernoon.com/the-art-of-humanizing-pull-requests-prs-b520588eb345)and respect the title of this pr.

2021-08-08 19:04 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
> +                            matchRatingViewModel.ratePlayers(matchRatingAdapter.getPlayerRatingList())
I am having trouble setting the value v at position p of a mutablelivedat<List<Float>>:

I was thinking something like `_userRatingList.value[position] = 9F`

but that's not working.. any ideas?

2021-08-08 19:08 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingViewModel.kt
> +                    val userUpdated = User(user.id, user.name, ((user.rating * user.numRatings) + rating) / (user.numRatings + 1), user.numRatings + 1)
Thanks, Sahil! Any suggestions on what the helper function should be?

2021-08-08 20:22 UTC, anthea-li commented on app/src/main/java/com/uwcs446/socialsports/ui/matchrating/MatchRatingActivity.kt
> +                            matchRatingViewModel.ratePlayers(matchRatingAdapter.getPlayerRatingList())
I think List is immutable, you have to use a MutableList to change the value.

2022-01-24 22:17 UTC, closed without merging