[WIP] [SFA-73] [SFA-103]  Profile Fragment Update Rating + Add NumRatings UI Element
SPahooja/SocialSports pull request #80
Opened 2021-08-07 20:54 UTC by akassab

# Preface 
- Builds off of  the user entity update durring #79 and uses the new db attribute rating and numRatings to display on the profile fragment

https://user-images.githubusercontent.com/15854649/128614689-ec498a9f-f8c6-48df-866d-200b410be32e.mp4

2021-08-07 21:44 UTC, aaronchlam requested changes
This PR cannot be merged into main. Please redirect it to the correct branch.

2021-08-07 21:48 UTC, SPahooja requested changes

2021-08-07 21:48 UTC, SPahooja commented on app/src/main/java/com/uwcs446/socialsports/ui/profile/ProfileViewModel.kt
> +        val authUser = currentUserRepository.getUser()!!
there was a reason null was handled, you cannot just assert non-null as a convenience. This is an extremely bad practice that could cause app crashes without much insight

2021-08-07 21:50 UTC, akassab commented
> This PR cannot be merged into main. Please redirect it to the correct branch.

Intended to be merged after #79 hence the title [WIP] :)

2021-08-07 21:51 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/profile/ProfileViewModel.kt
> +        val authUser = currentUserRepository.getUser()!!
In the case that it is NULL do we really want to show the user "Logged out." Is that app useful at that point?

2021-08-07 22:03 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/profile/ProfileViewModel.kt
> +        val authUser = currentUserRepository.getUser()!!
Right now the user can get into the profile fragment without logging in so this will crash the app. That's decidedly worse than showing "Logged out".

2021-08-07 22:05 UTC, aaronchlam commented
> > This PR cannot be merged into main. Please redirect it to the correct branch.
> 
> Intended to be merged after #79 hence the title [WIP] :)

You can still point it to the #79 branch. If #79 is merged into `main`, this will be redirected to `main`.

2021-08-07 23:46 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/profile/ProfileViewModel.kt
> +        val authUser = currentUserRepository.getUser()!!
Ok so its only a matter of extremely bad practice because we currently have a _extremly_ bad bug. OK!

2021-08-08 02:32 UTC, aaronchlam commented on app/src/main/java/com/uwcs446/socialsports/ui/profile/ProfileViewModel.kt
> +        val authUser = currentUserRepository.getUser()!!
It's still bad practice to assert non-null. We do use it in places where we know it to be not null but here there's no guarantees at all.

2021-08-08 04:12 UTC, akassab commented on app/src/main/java/com/uwcs446/socialsports/ui/profile/ProfileViewModel.kt
> +        val authUser = currentUserRepository.getUser()!!
Oh I see, I was under the impression it was guaranteed! Great catch!

2022-01-24 22:17 UTC, closed without merging